version: '3.7'

services:
  db:
    container_name: db
    image: postgres
    env_file:
      - ./.env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  migrator:
    container_name: migrator
    image: migrate/migrate
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./internal/migrations:/migrations
    command: -path=/migrations -database postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable up

  app:
    container_name: app
    build: .
    env_file:
      - ./.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${APP_PORT_GRPC}:${APP_PORT_GRPC}"
    depends_on:
      migrator:
        condition: service_completed_successfully      

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./internal/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  db_data: