name: main

on:
  push:
    branches:
      - main

env:
  REGISTRY: antgoncharik
  IMAGE_NAME: crypto-knight-api
  CONTAINER_NAME: crypto-knight-api
  DOCKERHUB_USERNAME: antgoncharik

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Build container image and push
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .
          docker login -u ${{ env.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 
          
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Copy docker compose file
        run: scp -i ${{ secrets.SSH_PRIVATE_KEY }} ./docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:./
        # uses: appleboy/scp-action@master
        # with:
          # host: ${{ secrets.SERVER_HOST }}
          # username: ${{ secrets.SERVER_USER }}
          # key: ${{ secrets.SSH_PRIVATE_KEY }}
          # source: "${{ github.workspace }}/docker-compose.yml"
          # source: "../../docker-compose.yml"
          # target: "./"

      - name: Run all services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.ENV_FILE }}" > .env
            # docker-compose down
            # docker-compose up -d
            rm -f .env
